# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

phone: "(978) 111 2222"
addres: "100 William T. Morrissey Blvd. Boston, MA 02125"
title: "Department of Computer Science"
email: "csinfo@cs.umb.edu"
#Removed Description from footer
description: >- # this means to ignore newlines until "baseurl:"
  UMass Boston
  Department of Computer Science

# baseurl to courses [path to courses] [example: /academics/courses/CS105]
pathToCourses: "/umbcs/academics/courses"

baseurl: "/umbcs" # the subpath of your site, e.g. /blog
url: "https://rodsk.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username: jekyll

facebook_url: https://www.facebook.com/umassboston
twitter_url: https://twitter.com/umassboston
linkedin_url: https://www.linkedin.com/school/umass-boston?pathWildcard=166578

# Build settings

# we are now using custom regular theme
#theme: minima
plugins:
  - jekyll-feed
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
